export {
  AGENTS_INSTRUCTIONS_RESOURCE_NAME,
  AGENTS_MD_DISPLAY_NAME,
  GLOBAL_SCOPE_LABEL,
  containedFileStem,
  formatOriginDisplayLabel,
  formatOriginKindLabel,
  formatResourceDisplayName,
  formatResourceScopeLabel,
  groupedOriginKind,
  inferContainedFileType,
  isAgentsMdResource,
  isPackageEntryFileName,
  packageDirectoryDisplayPath,
  resourceHumanName,
} from "../../../../src/ui/resource-display.ts";
