import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const detailsDir = join(import.meta.dir, "../docs/scenarios/details");
const outDir = join(import.meta.dir, "../src/generated");
const outFile = join(outDir, "scenarios.ts");

export interface GeneratedScenario {
  id: number;
  filename: string;
  title: string;
  frequency: string | null;
  status: string | null;
  summaryLines: string[];
  commands: string[];
}

function parseScenarioMetadata(
  id: number,
  markdown: string,
): Pick<GeneratedScenario, "title" | "frequency" | "status"> {
  const titleMatch = /^# Scenario \d+:\s*(.+)$/m.exec(markdown);
  const metaMatch =
    /^\*\*Frequency:\s*([^*]+)\*\*\s*·\s*\*\*Status:\s*([^*]+)\*\*/m.exec(
      markdown,
    );
  return {
    title: titleMatch?.[1]?.trim() ?? `Scenario ${id}`,
    frequency: metaMatch?.[1]?.trim() ?? null,
    status: metaMatch?.[2]?.trim() ?? null,
  };
}

function extractBashCommands(markdown: string): string[] {
  const commands: string[] = [];
  const blockPattern = /```bash\n([\s\S]*?)```/g;
  for (const match of markdown.matchAll(blockPattern)) {
    const block = match[1];
    if (!block) {
      continue;
    }
    for (const line of block.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) {
        continue;
      }
      commands.push(trimmed);
    }
  }
  return commands;
}

function summaryLines(markdown: string): string[] {
  const cut = markdown.indexOf("Typical commands:");
  return markdown
    .slice(0, cut < 0 ? markdown.length : cut)
    .split("\n")
    .slice(4)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("["));
}

function loadAll(): GeneratedScenario[] {
  if (!existsSync(detailsDir)) {
    throw new Error(`Missing scenarios directory: ${detailsDir}`);
  }
  const scenarios: GeneratedScenario[] = [];
  for (const name of readdirSync(detailsDir)) {
    const match = /^(\d{2})-/.exec(name);
    if (!match?.[1] || !name.endsWith(".md")) {
      continue;
    }
    const id = Number.parseInt(match[1], 10);
    const markdown = readFileSync(join(detailsDir, name), "utf-8");
    scenarios.push({
      id,
      filename: name,
      ...parseScenarioMetadata(id, markdown),
      summaryLines: summaryLines(markdown),
      commands: extractBashCommands(markdown),
    });
  }
  return scenarios.sort((left, right) => left.id - right.id);
}

const scenarios = loadAll();
mkdirSync(outDir, { recursive: true });
writeFileSync(
  outFile,
  `/* Generated by scripts/generate-scenarios.ts. Do not edit. */\n` +
    `export const GENERATED_SCENARIOS = ${JSON.stringify(scenarios, null, 2)} as const;\n`,
);
console.log(`Wrote ${scenarios.length} scenarios to ${outFile}`);
